class AppLocalizations {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_title': 'Auth System',
      'welcome': 'Welcome back',
      'login': 'Sign In',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'age': 'Age',
      'forgot_password': 'Forgot password?',
      'no_account': "Don't have an account? Sign up",
      'have_account': 'Already have an account? Sign in',
      'logout': 'Logout',
      'create_account': 'Create Account',
      'sign_in_to_continue': 'Sign in to continue',
      'my_apps': 'My Apps',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Appearance',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'fashion_store': 'Fashion Store',
      'fashion_desc': 'Shop the latest trends',
      'stream_flix': 'StreamFlix',
      'stream_desc': 'Movies & TV Shows',
      'social_chat': 'SocialChat',
      'social_desc': 'Connect with friends',
      'mens_wear': "Men",
      'womens_wear': 'Women',
      'kids_wear': 'Kids',
      'accessories': 'Accessories',
      'add_to_cart': 'Add to Cart',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'total': 'Total',
      'items': 'items',
      'empty_cart': 'Your cart is empty',
      'order_placed': 'Order placed successfully!',
      'product_details': 'Product Details',
      'quantity': 'Quantity',
      'size': 'Size',
      'color': 'Color',
      'in_stock': 'In Stock',
      'free_shipping': 'Free Shipping',
      'remove': 'Remove',
      'trending': 'Trending',
      'action': 'Action',
      'comedy': 'Comedy',
      'drama': 'Drama',
      'horror': 'Horror',
      'kids': 'Kids',
      'play': 'Watch Now',
      'my_list': 'My List',
      'messages': 'Messages',
      'friends': 'Friends',
      'groups': 'Groups',
      'status': 'Status',
      'send_message': 'New Message',
      'error': 'Error',
      'success': 'Success',
      'invalid_credentials': 'Invalid email or password',
      'email_exists': 'This email is already registered',
      'registration_success': 'Account created successfully',
      'age_restricted': 'Age restriction',
      'min_age_required': 'Minimum age required:',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'account_created': 'Member since',
      'last_login': 'Last login',
    },
    'tk': {
      'app_title': 'Giriş Ulgamy',
      'welcome': 'Hoş geldiňiz',
      'login': 'Giriş',
      'register': 'Hasap dörediň',
      'email': 'Email',
      'password': 'Parol',
      'name': 'At Familýa',
      'age': 'Ýaş',
      'forgot_password': 'Paroly unutdyňyzmy?',
      'no_account': 'Hasabyňyz ýokmy? Hasaba alyň',
      'have_account': 'Hasabyňyz barmy? Giriň',
      'logout': 'Çykmak',
      'create_account': 'Hasap Dörediň',
      'sign_in_to_continue': 'Dowam etmek üçin giriň',
      'my_apps': 'Programmalarym',
      'profile': 'Profil',
      'settings': 'Sazlamalar',
      'language': 'Dil',
      'theme': 'Görünüş',
      'light_mode': 'Ýagty',
      'dark_mode': 'Garaňky',
      'fashion_store': 'Moda Dükan',
      'fashion_desc': 'Iň täze modalar',
      'stream_flix': 'StreamFlix',
      'stream_desc': 'Film we seriallar',
      'social_chat': 'SosialÇat',
      'social_desc': 'Dostlaryňyz bilen habarlaşyň',
      'mens_wear': 'Erkekler',
      'womens_wear': 'Aýallar',
      'kids_wear': 'Çagalar',
      'accessories': 'Aksessuarlar',
      'add_to_cart': 'Sebede goş',
      'cart': 'Sebet',
      'checkout': 'Sargyt et',
      'total': 'Jemi',
      'items': 'haryt',
      'empty_cart': 'Sebet boş',
      'order_placed': 'Sargyt üstünlikli berildi!',
      'product_details': 'Haryt maglumaty',
      'quantity': 'Mukdar',
      'size': 'Ölçeg',
      'color': 'Reňk',
      'in_stock': 'Bardy',
      'free_shipping': 'Mugt eltip beriş',
      'remove': 'Aýyr',
      'trending': 'Meşhur',
      'action': 'Hereket',
      'comedy': 'Komediýa',
      'drama': 'Drama',
      'horror': 'Gorkunç',
      'kids': 'Çagalar',
      'play': 'Görmek',
      'my_list': 'Sanawym',
      'messages': 'Habarlar',
      'friends': 'Dostlar',
      'groups': 'Toparlar',
      'status': 'Ýagdaý',
      'send_message': 'Täze habar',
      'error': 'Ýalňyşlyk',
      'success': 'Üstünlikli',
      'invalid_credentials': 'Email ýa-da parol nädogry',
      'email_exists': 'Bu email eýýäm hasaba alyndy',
      'registration_success': 'Hasap üstünlikli döredildi',
      'age_restricted': 'Ýaş çäklendirmesi',
      'min_age_required': 'Iň az ýaş:',
      'edit_profile': 'Profili üýtget',
      'change_password': 'Paroly üýtget',
      'account_created': 'Hasap döredilen',
      'last_login': 'Soňky giriş',
    },
    'ru': {
      'app_title': 'Система Авторизации',
      'welcome': 'Добро пожаловать',
      'login': 'Войти',
      'register': 'Создать аккаунт',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'name': 'Полное имя',
      'age': 'Возраст',
      'forgot_password': 'Забыли пароль?',
      'no_account': 'Нет аккаунта? Зарегистрируйтесь',
      'have_account': 'Уже есть аккаунт? Войти',
      'logout': 'Выйти',
      'create_account': 'Создать аккаунт',
      'sign_in_to_continue': 'Войдите чтобы продолжить',
      'my_apps': 'Мои приложения',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'language': 'Язык',
      'theme': 'Оформление',
      'light_mode': 'Светлая',
      'dark_mode': 'Темная',
      'fashion_store': 'Магазин моды',
      'fashion_desc': 'Последние тренды',
      'stream_flix': 'StreamFlix',
      'stream_desc': 'Фильмы и сериалы',
      'social_chat': 'СоциалЧат',
      'social_desc': 'Общайтесь с друзьями',
      'mens_wear': 'Мужское',
      'womens_wear': 'Женское',
      'kids_wear': 'Детское',
      'accessories': 'Аксессуары',
      'add_to_cart': 'В корзину',
      'cart': 'Корзина',
      'checkout': 'Оформить заказ',
      'total': 'Итого',
      'items': 'товара',
      'empty_cart': 'Корзина пуста',
      'order_placed': 'Заказ успешно оформлен!',
      'product_details': 'Детали товара',
      'quantity': 'Количество',
      'size': 'Размер',
      'color': 'Цвет',
      'in_stock': 'В наличии',
      'free_shipping': 'Бесплатная доставка',
      'remove': 'Удалить',
      'trending': 'В тренде',
      'action': 'Боевик',
      'comedy': 'Комедия',
      'drama': 'Драма',
      'horror': 'Ужасы',
      'kids': 'Детям',
      'play': 'Смотреть',
      'my_list': 'Мой список',
      'messages': 'Сообщения',
      'friends': 'Друзья',
      'groups': 'Группы',
      'status': 'Статус',
      'send_message': 'Новое сообщение',
      'error': 'Ошибка',
      'success': 'Успешно',
      'invalid_credentials': 'Неверный email или пароль',
      'email_exists': 'Email уже зарегистрирован',
      'registration_success': 'Аккаунт успешно создан',
      'age_restricted': 'Ограничение по возрасту',
      'min_age_required': 'Минимальный возраст:',
      'edit_profile': 'Редактировать',
      'change_password': 'Изменить пароль',
      'account_created': 'Участник с',
      'last_login': 'Последний вход',
    },
  };

  static String translate(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['en']?[key] ?? key;
  }

  static List<String> get supportedLocales => ['en', 'tk', 'ru'];

  static String getLanguageName(String locale) {
    switch (locale) {
      case 'en': return 'EN';
      case 'tk': return 'TK';
      case 'ru': return 'RU';
      default: return 'EN';
    }
  }

  static String getFullLanguageName(String locale) {
    switch (locale) {
      case 'en': return 'English';
      case 'tk': return 'Türkmençe';
      case 'ru': return 'Русский';
      default: return 'English';
    }
  }
}
